Silabalkan user registration
blumilksoftware/interns2024c pull request #18
Opened 2024-12-02 11:32 UTC by Silabalkan

2024-12-02 12:00 UTC, EwelinaSkrzypacz reviewed
1. Please resolve conflicts
2. Please change pr title - we have a rule that pr title should look like this:

#issue-number - title

So in this case, we should give title like 
#3 - user auth

And also please remember that in pr description we should write down every issue that is connected with pr or any issues that should bo closed after merging this pr. Something like: This should close #issue-number

3. Please don't push `.env` file

2024-12-02 13:02 UTC, senagokhan approved these changes, later dismissed

2024-12-02 13:03 UTC, EwelinaSkrzypacz requested changes
Checks are failed - please fix this

2024-12-02 13:03 UTC, EwelinaSkrzypacz commented on .gitignore
> +
```suggestion
```

2024-12-02 13:44 UTC, EwelinaSkrzypacz commented on .gitignore
> +
At the end of the file should be only one empty line

2024-12-03 13:18 UTC, EwelinaSkrzypacz reviewed
1. Please fix all warnings from GitHub - like this

![image](https://github.com/user-attachments/assets/44c495d8-d912-4f33-9faa-de60d7d4f736)

2. At our company, we avoid leaving comments in the code unless absolutely necessary. We believe that code should be self-explanatory. That said, if you really feel a comment is needed, don’t worry—we can live with it. 😄 Let’s just keep it to a minimum.

I know that most of comments are from Laravel Breeze and fresh Laravel installation, but I think we can remove them

2024-12-03 13:18 UTC, EwelinaSkrzypacz commented on vite.config.js
> +
```suggestion
```

2024-12-03 13:18 UTC, EwelinaSkrzypacz commented on resources/js/bootstrap.ts
> +// window için tür tanımlama
:eyes:

If you really need this comment, please write it in English

2024-12-04 05:06 UTC, EwelinaSkrzypacz commented on vite.config.js
> +}
Now empty line at the end of the file is missing :eyes:

2024-12-05 05:17 UTC, EwelinaSkrzypacz reviewed
1. Check is failed - please run `make fix` - it should fix all errors
2. Extra blank lines have been unnecessarily added at the end of the file, resulting in two blank lines. This clutters the code and doesn't follow standard formatting practices. Please keep only one blank line at the end.

2024-12-05 05:17 UTC, EwelinaSkrzypacz commented on package.json
> +        "tailwindcss": "^3.4.16",
It should be in `dependencies` not in `devDependencies`

2024-12-05 05:17 UTC, EwelinaSkrzypacz commented on resources/js/Pages/Auth/ForgotPassword.vue
> +
These two empty lines can be removed

2024-12-05 05:17 UTC, EwelinaSkrzypacz commented on resources/js/Pages/Auth/Login.vue
> +
This extra empty line can be removed

2024-12-05 07:53 UTC, EwelinaSkrzypacz commented
I think that tasks #4 and #5 can be closed because in Laravel Breeze out of the box we have features like login to application and reset password - so please write in pr description "This should close " and task number.

2024-12-06 05:03 UTC, EwelinaSkrzypacz reviewed
Please fix GitHub errors and warnings in `resources/js/Pages/Auth/VerifyEmail.vue`. It's just some on them :point_down: 

![image](https://github.com/user-attachments/assets/ff0f20f8-0b93-4f7a-a220-eecad3923b22)

2024-12-06 05:03 UTC, EwelinaSkrzypacz commented on resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue
> +
Remove this extra empty line; please search other places where is extra empty line/lines and remove them.

2024-12-06 05:03 UTC, EwelinaSkrzypacz commented on resources/js/app.ts
> +
```suggestion
```

2024-12-06 12:53 UTC, EwelinaSkrzypacz commented on resources/js/Pages/Profile/Edit.vue
> +
unnecessary empty line

2024-12-09 06:23 UTC, EwelinaSkrzypacz approved these changes, later dismissed

2024-12-12 14:02 UTC, selinuluca approved these changes

2024-12-12 14:03 UTC, EwelinaSkrzypacz approved these changes

2024-12-12 14:18 UTC, merged